# Generated by Django 5.1.3 on 2025-01-28 08:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='when',
            field=models.DateField(blank=True, db_comment='Date of application.', default=django.utils.timezone.now),
        ),
    ]
