# Generated by Django 5.1.3 on 2026-02-23 01:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='when',
            field=models.DateField(blank=True, db_comment='Date of application.', default=django.utils.timezone.localtime),
        ),
    ]
