# Generated by Django 6.0.6 on 2026-06-30 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobapplication_posting'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(db_comment='Primary key', help_text='The primary key for the job post', primary_key=True, serialize=False, verbose_name='id')),
                ('raw_url', models.URLField(db_comment='The raw URL of the job posting.', help_text='The raw URL from the address bar for a job posting, with all the tracking and other cruft included.', max_length=2048, unique=True, verbose_name='raw job posting url')),
                ('clean_url', models.URLField(blank=True, db_comment='The cleaned up URL of job posting, if available.', help_text='The cleaned up URL for the job posting, if applicable. Use notes for other job sources', max_length=2048, null=True, verbose_name='clean job posting url')),
                ('http_status', models.IntegerField(db_comment='The HTTP status returned when requesting the job posting.', help_text='The HTTP status returned when requesting the job posting.', verbose_name='the HTTP status returned when requesting the job posting.')),
                ('status_text', models.CharField(db_comment='The status text returned when requesting the job posting.', help_text='The status text returned when requesting the job posting.', max_length=256, verbose_name='the status text returned when requesting the job posting.')),
                ('contents', models.TextField(db_comment='The raw page contents for the job post.', help_text='The raw page contents for the job post.', verbose_name='job post contents')),
                ('description', models.TextField(blank=True, db_comment='The description according to the job post.', help_text='The description according to the job post.', null=True, verbose_name='job post description')),
                ('company', models.CharField(db_comment='Name of company.', help_text='The name of the company.', max_length=64, verbose_name='company name')),
                ('title', models.CharField(db_comment='Job title.', help_text='The job title.', max_length=128, verbose_name='job title')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Record created at.', help_text='When the record was created', null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='Record last updated at.', help_text='When the record was last updated', verbose_name='updated_at')),
            ],
            options={
                'db_table': 'job_posts',
                'db_table_comment': 'Tracks the actual job postings for teaching an LLM to scrape for us.',
            },
        ),
        migrations.AlterModelTableComment(
            name='jobapplication',
            table_comment='Tracks a job application made by a user.',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='saved_posting',
            field=models.ForeignKey(blank=True, db_comment='The saved job posting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_post', to='applications.jobpost', verbose_name='saved job post id'),
        ),
    ]
