# Generated by Django 5.1.3 on 2026-03-05 05:06

from django.db import migrations, models
from django.db.models import F

def copy_value_from_when_to_created_at(apps, schema_editor):
    """Use the value from the when field to initialze the created_at field while adding it."""

    MyModel = apps.get_model('applications', 'JobApplication')
    db_alias = schema_editor.connection.alias
    MyModel.objects.using(db_alias).all().update(created_at=F('when'))


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobapplication_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejected',
            field=models.DateField(blank=True, db_comment='Date of rejection notice.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_comment='Record created at.', null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_comment='Record last updated at.'),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='notes',
            field=models.CharField(blank=True, db_comment='Notes', max_length=256),
        ),
        migrations.RunPython(copy_value_from_when_to_created_at, reverse_code=migrations.RunPython.noop),
    ]
