services:
  py-wsgi:
    build:
      context: .
      dockerfile: ./docker/py-wsgi/Dockerfile
      tags:
        - job-application-tracker-py-wsgi:latest
      target: production
    image: job-application-tracker-py-wsgi
    env_file:
      - ./.env
    command: gunicorn job-application-tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/job-application-tracker/web/staticfiles
      - media_volume:/var/www/job-application-tracker/web/mediafiles
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
      tags:
        - job-application-tracker-web:latest
    image: job-application-tracker-web
    volumes:
      - static_volume:/var/www/job-application-tracker/web/staticfiles
      - media_volume:/var/www/job-application-tracker/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - py-wsgi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  static_volume:
  media_volume:
