services:
  py-wsgi:
    build:
      context: .
      dockerfile: ./docker/py-wsgi/Dockerfile
      tags:
        - ${REGISTRY}/job-application-tracker-py-wsgi:${TAG}
        - ${REGISTRY}/job-application-tracker-py-wsgi:latest
      target: production
    image: ${REGISTRY}/job-application-tracker-py-wsgi
    command: gunicorn job_application_tracker.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/var/www/job-application-tracker/web/staticfiles
      - media_volume:/var/www/job-application-tracker/web/mediafiles
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE}
    secrets:
      - source: job-application-tracker-env
        target: /var/www/job-application-tracker/web/.env
        mode: 0400
        uid: '0'
        gid: '0'


  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
      tags:
        - ${REGISTRY}/job-application-tracker-web:${TAG}
        - ${REGISTRY}/job-application-tracker-web:latest
    image: ${REGISTRY}/job-application-tracker-web
    volumes:
      - static_volume:/var/www/job-application-tracker/web/staticfiles
      - media_volume:/var/www/job-application-tracker/web/mediafiles
    ports:
      - 8000:80
    depends_on:
      - py-wsgi
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == ${DOCKER_NODE}

#### BUILD ONLY START ####

  tester:
    build:
      context: .
      dockerfile: ./docker/py-wsgi/Dockerfile
      tags:
        - job-application-tracker-tester
      target: tester
    image: job-application-tracker-tester
    env_file:
      - ./.env
    profiles: [testing]
    command: /bin/sh -c "pylint --disable=fixme . && coverage run --branch ./manage.py test && coverage combine && coverage html && coverage xml && coverage report && ls -la"

#### BUILD ONLY END ####

volumes:
  static_volume:
  media_volume:


secrets:
  job-application-tracker-env:
    external: true
