[build-system]
requires = ["setuptools",  "setuptools-scm"]
build_backend = "setuptools.build_meta"

[project]
name = "job_application_tracker"
dynamic = ["version"]
description = "A tracking system for job applications"
readme = { file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.13"
license-files = ["LICENSE"]
authors = [
    {name = "Douglas Needham", email = "cinnion@gmail.com" },
]
dependencies = [
    # Django
    "Django >= 6.0.4",
    # Django allauth
    "django-allauth >= 65.18.0",
    # Advanced .env support
    "django-environ >= 0.13.0",
    # Webpack
    "django-webpack-loader >= 3.2.3",
    # Password validators
    "django-password-validators >= 1.7.3",
    # Crispy Forms
    "crispy-bootstrap5 >= 2026.3",
    "django-crispy-forms >= 2.6",
    # For DataTable support
    "django-ajax-datatable >= 4.5.0",
    "djangorestframework >= 3.17.1",
    # For tweaking form widgets
    "django-widget-tweaks >= 1.5.1",
    # Google sheet access
    "google-api-python-client >= 2.194.0",
    "google-auth-oauthlib >= 1.3.1",
    "google-cloud-api-keys >= 0.8.0",
    # Status proto mapping for gRPC
    "grpcio-status >= 1.80.0",
    # WSGI server
    "gunicorn >= 25.3.0",
    # Database
    "psycopg[binary,pool] >= 3.3.3",
    # Type hints for Python 3.8+
    "typing_extensions >= 4.15.0",
    # For page scraping.
    "playwright>=1.60.0",
    "beautifulsoup4>=4.15.0",
]

[project.urls]
Homepage = "https://www.ka8zrt.com"
Documentation = "https://www.ka8zrt.com"

[project.scripts]
manage = "job_application_tracker.manage:main"

[project.optional-dependencies]

[dependency-groups]
test = [
    # Black code formatter
    "black>=26.5.1",
    # Coverage tool
    "coverage >= 7.13.5",
    # Mypy static type checker
    "mypy>=2.1.0",
    # Framework for managing commit hooks.
    "pre-commit>=4.6.0",
    # For functional testing.
    "pytest-playwright>=0.8.0",
]
dev = [
    # Also include the dependencies from the test group.
    {include-group = "test"},
    # Django Debug Toolbar
    "django-debug-toolbar >= 6.3.0",
    # Django extensions
    "django-extensions >= 4.1",
    # Upgrade tool
    "django-upgrade >= 1.30.0",
    # DRF stubs for code insight.
    "djangorestframework-stubs >= 3.16.9",
    # To see dependency tree
    "pipdeptree >= 2.35.1",
    # Lint
    "pylint[spelling] >= 4.0.6",
    # Lint extensions for djangobugfixes",
    "pylint-django >= 2.7.0",
    # Lint - Add specific rule ignores based on the file.
    "pylint-per-file-ignores >= 3.2.1",
    # Setuptools-scm, for integrating our dynamic versioning with git tags.
    "setuptools-scm >= 10.0.5",
    # Version bump tool
    "tbump >= 6.11.0",
    # Towncrier
    "towncrier >= 25.8.0",
    # To give us parameterized unit tests in unittest.
    "unittest-parametrize >= 1.8.0",
]

[tool.black]
line-length = 120
target-version = ["py312", "py313"]
extend-exclude = '''
   # Exclude folders which should not be formatted
   \.idea
   | node_modules
'''
check = true
diff = true

[tool.coverage.run]
branch = true
source = [ "." ]
dynamic_context = "test_function"
data_file = ".coverage"
parallel = true
omit = [
    # Virtual environment and build artifacts
    ".venv/*",
    "htmlcov/",
    "*/node_modules/*",
    "docker/",

    # Django specific exclusions
    "*/migrations/*",
    "*/static/*",
    "*/templates/*",
    "*/__init__.py",
    "manage.py",
    "job_application_tracker/asgi.py",
    "job_application_tracker/settings.py",
    "job_application_tracker/urls.py",
    "job_application_tracker/wsgi.py",

    # Test files themselves
    "core/test.py",
    "*/tests/*",
    "tests.py",
]

[tool.coverage.report]
skip_empty = true               # Don't report on empty files (those that have no statements)
fail_under = 80                 # Fail the build if the total coverage is below this minimum percentage
show_missing = true             # Show missing lines

[tool.coverage.html]
directory = "htmlcov"           # Directory to write the HTML report files to
show_contexts = true            # Show the context for each covered line in the HTML report
title = "Job Application Tracker Test Coverage Report"          # Title for the HTML report

[tool.coverage.xml]
output = "coverage.xml"

[tool.ReportCoverage]
fail_under = 60
warn_under = 70

[tool.mypy]
python_version = "3.13"
files = [
    "."
]
#exclude = (?x)(
#    ^doc                # doc, like it would find anything there...
#    | ^htmlcov          # htmlcov
#    | __pycache__       # Cached/compiled python files
#    | node_modules      # NPM packages
#    | \..*              # Files/directories starting with a ".", like ".git", ".idea" or ".venv".
#    )
exclude_gitignore = true

# Error message format
show_error_code_links = true
pretty = true

# Not yet on strict. :) It gives me nearly 800 errors.
#strict = true

# Strictness flags
check_untyped_defs = false
disallow_any_generics = false
disallow_incomplete_defs = false
disallow_subclassing_any = false
disallow_untyped_calls = false
disallow_untyped_decorators = true
disallow_untyped_defs = false
no_implicit_optional = false
no_implicit_reexport = false
strict_equality = false
warn_redundant_casts = false
warn_return_any = false
warn_unused_configs = false
warn_unused_ignores = true

# Miscellaneous strictness flags
enable_error_code = "ignore-without-code"

# Miscellaneous
scripts_are_modules = true

#[[tool.mypy.overrides]]
#ignore_missing_imports = true
#module = [
#]

[tool.pylint.main]
django-settings-module="job_application_tracker.settings"
load-plugins = [
    "pylint_django",
    "pylint_per_file_ignores",
]
max-line-length = 120
ignore = [
    ".git",
    ".venv",
    "__pycache__",
    "manage.py",
    "node_modules"
]
jobs = 0
persistent = true
recursive = true
reports = true
score = true
source-roots = "."

[tool.pylint.'messages control']
per-file-ignores = [
    "*/forms.py:too-few-public-methods",
    "*/migrations/*:line-too-long,invalid-name,missing-module-docstring,missing-class-docstring",
    "*/models.py:too-few-public-methods",
    "*/tests/*:duplicate-code,missing-function-docstring,too-many-ancestors,too-many-public-methods",
    "*/urls.py:invalid-name",
    "*/views.py:too-many-ancestors",
    "applications/tests/test_authenticated_user.py:too-many-lines",
    "core/tests/mixins.py:line-too-long,too-many-arguments,too-many-positional-arguments",
    "job_application_tracker/middleware.py:too-few-public-methods",
    "job_application_tracker/settings.py:line-too-long,consider-using-f-string,invalid-name",
    "users/tests/test_unauthenticated_userresetview.py:line-too-long",
    "users/views.py:duplicate-code"
]

[tool.setuptools]
py-modules = [
    "applications",
    "applications_ini",
    "job_application_tracker",
]

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
#version_scheme = "release-branch-semver"	# Uses the branch name.

[tool.tbump]
github_url = "https://github.com/cinnion/job-application-tracker/"

[tool.tbump.version]
current = "2.0.3"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

# For each file to patch, add a [[tool.tbump.file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
[[tool.tbump.file]]
src = "pyproject.toml"
version_template = "doc/whatsnew/{major}/{major}.{minor}/index.rst"
search = 'filename = "{current_version}"'

# You can specify a list of commands to
# run after the files have been patched
# and before the git commit is made

#  [[tool.tbump.before_commit]]
#  name = "check changelog"
#  cmd = "grep -q {new_version} Changelog.rst"
[[tool.tbump.before_commit]]
name = "Build towncrier files"
cmd = "towncrier build --version={new_version}"

# Or run some commands after the git tag and the branch
# have been pushed:
#  [[tool.tbump.after_push]]
#  name = "publish"
#  cmd = "./publish.sh"

[tool.towncrier]
package = "job_application_tracker"
directory = "doc/whatsnew/fragments"
filename = "doc/whatsnew/2/2.0/index.rst"
template = "doc/whatsnew/fragments/_template.rst"
issue_format = "`#{issue} <https://github.com/cinnion/job-application-tracker/issues/{issue}>`_"
wrap = false

[[tool.towncrier.type]]
directory = "feature"
name = "New Features"
showcontent = true

[[tool.towncrier.type]]
directory = "bugfix"
name = "Other Bug Fixes"
showcontent = true

[[tool.towncrier.type]]
directory = "doc"
name = "Documentation Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "other"
name = "Other Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "internal"
name = "Internal Changes"
showcontent = true

[[tool.towncrier.type]]
directory = "performance"
name = "Performance Improvements"
showcontent = true

[tool.uv]
compile-bytecode = true
