"""
Django settings for job-application-tracker project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Default values come from django.conf.global_settings.py, and this file has been reordered to match that file, with
settings for extensions added at the end of the file.
"""
import os
from pathlib import Path

import environ

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Initialize the env object.
env = environ.Env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from the .env file.
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Set our DEBUG value
DEBUG = env.bool('DEBUG', False)

# People who get code error notifications.
ADMINS = env.list('ADMINS', default=[])

# Hostts/domain names that are valid for this site.
ALLOWED_HOSTS = env.list('MYHOSTNAMES')

# Local time zone for this installation.
TIME_ZONE = env.str('TIME_ZONE', 'America/New_York')

# If you set this to True, Django will use timezone-aware datetimes.
USE_TZ = env.bool('USE_TZ', True)

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Language code for this installation. Valid choices can be found here:
# https://www.iana.org/assignments/language-subtag-registry/
# If LANGUAGE_CODE is not listed in LANGUAGES (below), the project must
# provide the necessary translations and locale definitions.
LANGUAGE_CODE = env.str('LANGUAGE_CODE', 'en-us')

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = env.bool('USE_I18N', True)

# Email address that error messages come from.
SERVER_EMAIL = env('SERVER_EMAIL')

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': env.db_url()
}

# Email backend
# https://docs.djangoproject.com/en/6.0/topics/email/
EMAIL_BACKEND = env('EMAIL_BACKEND')
split_list = EMAIL_BACKEND.split('.')
if split_list[-2] == 'filebased':
    EMAIL_FILE_PATH = env('EMAIL_FILE_PATH')
elif split_list[-2] == 'smtp':
    # Host for sending email.
    EMAIL_HOST = env('EMAIL_HOST')
    # Port for sending email.
    EMAIL_PORT = env.int('EMAIL_PORT', 25)
    # Optional SMTP authentication information for EMAIL_HOST.
    EMAIL_HOST_USER = env.str('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', False)
    EMAIL_USE_SSL = env.bool('EMAIL_USE_SSL', False)
    EMAIL_SSL_KEYFILE = env.str('EMAIL_SSL_KEYFILE', None)
    EMAIL_SSL_CERTFILE = env.str('EMAIL_SSL_CERTFILE', None)
    EMAIL_TIMEOUT = env.int('EMAIL_TIMEOUT', None)
elif split_list[-2] == 'console':
    pass
elif split_list[-2] == 'locmem':
    pass
elif split_list[-2] == 'dummy':
    pass
else:
    raise environ.ImproperlyConfigured('Unknown mail backend: {}'.format(split_list[-2]))
del split_list

# List of strings representing installed apps.
INSTALLED_APPS = [
    'users',
    'applications',
    'applications_api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'allauth',
    'allauth.account',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_password_validators',
    'rest_framework',
    'webpack_loader',
    'widget_tweaks',
    'django_js_reverse',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'job_application_tracker.context_processors.build_info_processor',
                'job_application_tracker.context_processors.site_name_processor',
            ],
        },
    },
]

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

# Default email address to use for various automated correspondence from
# the site managers.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')

# A secret key for this particular Django installation. Used in secret-key
# hashing algorithms. Set this in your settings, or Django will complain
# loudly.
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Absolute path to the directory static files should be collected to.
# Example: "/var/www/example.com/static/"
STATIC_ROOT = "staticfiles/"

# URL that handles the static files served from STATIC_ROOT.
# Example: "http://example.com/static/", "http://static.example.com/"
STATIC_URL = 'static/'

USE_X_FORWARDED_HOST = env.bool('USE_X_FORWARDED_HOST', True)
USE_X_FORWARDED_PORT = env.bool('USE_X_FORWARDED_PORT', True)

# The Python dotted path to the WSGI application that Django's internal server
# (runserver) will use. If `None`, the return value of
# 'django.core.wsgi.get_wsgi_application' is used, thus preserving the same
# behavior as previous versions of Django. Otherwise this should point to an
# actual WSGI application object.
WSGI_APPLICATION = 'job_application_tracker.wsgi.application'

# If your Django app is behind a proxy that sets a header to specify secure
# connections, AND that proxy ensures that user-submitted headers with the
# same name are ignored (so that people can't spoof it), set this value to
# a tuple of (header_name, header_value). For any requests that come in with
# that header/value, request.is_secure() will return True.
# WARNING! Only set this if you fully understand what you're doing. Otherwise,
# you may be opening yourself up to a security risk.
SECURE_PROXY_SSL_HEADER = env.tuple('SECURE_PROXY_SSL_HEADER', default=('HTTP_X_FORWARDED_PROTO', 'https'))

##############
# MIDDLEWARE #
##############

# List of middleware to use. Order is important; in the request phase, these
# middleware will be applied in the order given, and in the response
# phase the middleware will be applied in reverse order.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

# Whether the session cookie should be secure (https:// only).
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', True)

##################
# AUTHENTICATION #
##################

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'account_login'

LOGOUT_REDIRECT_URL = 'home'

LOGIN_REDIRECT_URL = 'home'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'django_password_validators.password_character_requirements.password_validation.PasswordCharacterValidator',
        'OPTIONS': {
            'min_length_digit': 1,
            'min_length_alpha': 4,
            'min_length_special': 1,
            'min_length_lower': 1,
            'min_length_upper': 1,
            'special_characters': " ~!@#$%^&*()_+-{}\":;'[]"
        },
    },
]

########
# CSRF #
########

# Settings for CSRF cookie.
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', True)
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS')

###############
# STATICFILES #
###############

# A list of locations of additional static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# The location for the root of our URLs.
ROOT_URLCONF = 'job_application_tracker.urls'

####################################################
# Custom settings and application related settings #
####################################################

# Get our site name and admins
SITE_NAME = env('SITE_NAME')

# Get our environment ("development", "testing", "production")
DJANGO_ENV = env('DJANGO_ENV', default='production')

# Do our development overrides
if DJANGO_ENV == 'development':
    INSTALLED_APPS += [
        "django_extensions",
        "debug_toolbar",
    ]

    MIDDLEWARE = [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
        *MIDDLEWARE
    ]

    INTERNAL_IPS = [
        "127.0.0.1",
        "192.168.8.194",
    ]

################
# applications #
################

####################
# applications_api #
####################

###########
# allauth #
###########

ACCOUNT_VERIFICATION_METHOD = "email"
ACCOUNT_SIGNUP_FIELDS = [
    "username*",
    "email*",
    "email2*",
    "password1*",
    "password2*",
]
ACCOUNT_SIGNUP_FORM_HONEYPOT_FIELD = "phone_number"
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

####################################
# crispy_forms / crispy_bootstrap5 #
####################################
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

##################
# rest_framework #
##################

#####################
# django-js-reverse #
#####################
JS_REVERSE_OUTPUT_PATH = "static/js"
JS_REVERSE_JS_GLOBAL_OBJECT_NAME = "window"

##################
# webpack_loader #
##################
if DJANGO_ENV != 'testing':
    WEBPACK_LOADER = {
        'DEFAULT': {
            'STATS_FILE': os.path.join(STATIC_URL, 'webpack_bundles/webpack-stats.json'),
        },
        'APPLICATION_DETAILS': {
            'STATS_FILE': os.path.join(STATIC_URL, 'webpack_bundles/webpack-application-details-stats.json'),
        },
    }
else:
    WEBPACK_LOADER = {
        'DEFAULT': {
            'LOADER_CLASS': 'webpack_loader.loaders.FakeWebpackLoader',
        }
    }

##################
# Obscura server #
##################
OBSCURA_SERVER_CDP_URL = env('OBSCURA_SERVER_CDP_URL', default='ws://127.0.0.1:9222')
